INSERT INTO COUNTRY  VALUES ( 1,'Europe','MKD' );


INSERT INTO AUTHOR VALUES (2, 'Marko','Zoreski',1 );
INSERT INTO AUTHOR VALUES ( 21,'Zoran','Zaev',1 );


INSERT INTO BOOK VALUES ( 1,34,'NOVEL','Harry Potter',21 );
INSERT INTO BOOK VALUES ( 2,2,'THRILER','Stuart Little',2 );

INSERT INTO BOOK VALUES ( 3,17,'FANTASY','Gilgamesh',21 );
INSERT INTO BOOK VALUES ( 4,20,'HISTORY','Illiad',2 );

INSERT INTO BOOK VALUES ( 5,6,'BIOGRAPHY','Odyssey',21 );
INSERT INTO BOOK VALUES ( 6,1,'CLASSICS','Twilight',2 );
INSERT INTO BOOK VALUES ( 7,2,'DRAMA','Hunger Games',21 );
INSERT INTO BOOK VALUES ( 8,0,'HISTORY','Donato Charrissi',2 );
INSERT INTO BOOK VALUES ( 9,9,'FANTASY','The Shining',21 );
INSERT INTO BOOK VALUES ( 10,42,'CLASSICS','Batman',2 );
INSERT INTO BOOK VALUES ( 11,14,'FANTASY','Time Traveler',21 );
INSERT INTO BOOK VALUES ( 12,22,'DRAMA','Time Machine',2 );